// Generated by CoffeeScript 2.5.1
var ExampleRecursiveMenu, h, menuToggleReducer, menuToggleReducerState;

import {
  createElement,
  useState,
  useEffect,
  useRef,
  useReducer
} from 'react';

import {
  Layout,
  In,
  Box,
  Row,
  Menu,
  Section,
  SectionLabel,
  Style,
  Separator
} from '../components';

h = createElement;

menuToggleReducerState = {};

menuToggleReducer = function(state, {menu_name, item_name}) {
  return Object.assign({}, state, {
    [`${menu_name}`]: item_name
  });
};

import ExampleDemoBox from './ExampleDemoBox.coffee';

ExampleRecursiveMenu = function(props) {
  var dispatchMenuState, menu_state, onSelectRecursiveMenuItem, renderBox, renderRecursiveMenu;
  [menu_state, dispatchMenuState] = useReducer(menuToggleReducer, menuToggleReducerState);
  onSelectRecursiveMenuItem = function(menu_name, item_name) {
    // log 'on SELECT',menu_name,'->',item_name
    return dispatchMenuState({
      menu_name: menu_name,
      item_name: item_name
    });
  };
  renderBox = function() {
    return h(ExampleDemoBox);
  };
  renderRecursiveMenu = function(menu_name, level = 0, vert = true) {
    return h(Menu, {
      vert: vert != null ? vert : level % 2 === 0,
      // align: level == 0 &&  || undefined
      // position: level == 0 && [100,100] || undefined
      select: menu_state[menu_name],
      onSelect: function(item_name) {
        return onSelectRecursiveMenuItem(menu_name, item_name);
      },
      items: {
        [`${menu_name}-BOX1`]: renderBox,
        [`${menu_name}-1`]: renderRecursiveMenu.bind(null, `${menu_name}-1`, level + 1),
        [`${menu_name}-2`]: renderRecursiveMenu.bind(null, `${menu_name}-2`, level + 1),
        [`${menu_name}-BOX2`]: renderBox,
        [`${menu_name}-3`]: renderRecursiveMenu.bind(null, `${menu_name}-3`, level + 1),
        [`${menu_name}-4`]: renderRecursiveMenu.bind(null, `${menu_name}-4`, level + 1),
        [`${menu_name}-BOX3`]: renderBox
      }
    });
  };
  return renderRecursiveMenu(props.name, 0, props.vert);
};

export default ExampleRecursiveMenu;
